name: Download Unit Data

on:
  workflow_dispatch:
    inputs:
      client-name:
        description: Client Name
        required: true

      persona:
        description: Persona
        required: true

      table-name:
        description: SQL Table Name
        required: true

      status-column:
        description: Status Column
        required: false
        default: status

      output-file:
        description: Output Excel File
        required: false
        default: output.xlsx

jobs:
  generate_excel:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install ODBC Driver 18 for SQL Server
        run: |
          sudo apt-get update
          sudo apt-get install -y curl gnupg2 unixodbc-dev
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --dearmor -o /usr/share/keyrings/microsoft-prod.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft-prod.gpg] https://packages.microsoft.com/ubuntu/22.04/prod jammy main" | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Execute Script
        run: |
          python scripts/download_unit_data.py \
            --client-name "${{ github.event.inputs.client-name }}" \
            --persona "${{ github.event.inputs.persona }}" \
            --table-name "${{ github.event.inputs.table-name }}" \
            --status-column "${{ github.event.inputs.status-column }}" \
            --output-file "${{ github.event.inputs.output-file }}"
